version: "3"

services:
  rateapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./docker_volumes/sockets:/run/gunicorn
      - ./docker_volumes/log/gunicorn:/var/log/gunicorn
    security_opt:
      - "no-new-privileges"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - rateapi
    volumes:
      - ./docker_volumes/sockets:/run/gunicorn
      - ./docker_volumes/log/nginx:/var/log/nginx
    security_opt:
      - "no-new-privileges"
    restart: always

volumes:
  docker_volumes:

# docker compose up -d --build
# docker compose down