version: "3"

services:
  rateapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./socket_volume:/run/gunicorn
    security_opt:
      - "no-new-privileges"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - rateapi
    volumes:
      - ./socket_volume:/run/gunicorn
    security_opt:
      - "no-new-privileges"

volumes:
  socket_volume:

# docker compose up -d --build
# docker compose down